# Generated by Django 3.0.3 on 2021-01-04 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unishop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='unishop.Shop'),
        ),
    ]
