# Generated by Django 3.0.3 on 2021-01-13 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unishop', '0002_auto_20210104_1651'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shop',
            table='Shop',
        ),
    ]
