# Generated by Django 3.0.3 on 2021-01-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unishop', '0004_auto_20210113_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='image_name',
            field=models.TextField(null=True),
        ),
    ]
