# Generated by Django 3.0.3 on 2021-01-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unishop', '0006_auto_20210113_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image_name',
            field=models.CharField(default='/static/unishop/images/shop2/png', max_length=200),
            preserve_default=False,
        ),
    ]
