# Generated by Django 3.0.3 on 2021-01-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unishop', '0007_auto_20210113_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
